import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');
const styles = StyleSheet.create({
  loginContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    backgroundColor: '#33ffeb',
  },
  emailInput: {
    width: width - 70,
    height: 40,
    borderWidth: 1,
    fontSize: 16,
    padding: 10,
    borderColor: 'black',
    marginTop: 10,
  },
  recipeInput: {
    width: width - 70,
    height: 40,
    borderWidth: 1,
    fontSize: 16,
    padding: 10,
    marginTop: 10,
  },
  loginbutton: {
    width: width / 2,
    height: 40,
    marginTop: 10,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#107498',
  },
  addRecipeButton: {
    width: width - 40,
    height: 40,
    borderWidth: 1,
    marginTop: 15,
    borderRadius: 15,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#107498',
  },
  imagebuttonstyle: {
    width: width / 3,
    height: 40,
    borderWidth: 1,
    marginTop: 10,
    borderRadius: 15,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#107498',
  },
  loginbuttonTxt: { fontSize: 16, fontWeight: 'bold', color: 'white' },
  insteadText: { color: '#841584', fontSize: 16 },
  pickerModalTextContainer: {
    width: width / 1.5,
    height: 40,
    borderWidth: 1,
    padding: 10,
    flexDirection: 'row',
    marginTop: 10,
  },
  addContainer: {
    flexGrow: 1,
    padding: 15,
    marginTop: 50,

  },
  stepsContainer: {
    height: height / 3, borderColor: 'black', borderRadius: 10, borderWidth: 1, marginTop: 10,
  },
  imageView: {
    height: 150,
    width: width / 2,
    marginTop: 15,
    borderColor: 'black',
    borderWidth: 1,
  },
  imagestyle: {
    height: 150,
    width: width / 2,
  },
  stepsText: { height: height / 3, padding: 20 },
  headerText: { fontSize: 16 },
  rowBack: {
    alignItems: 'center',
    backgroundColor: '#DDD',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 15,
  },
  backRightBtn: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    width: 75,
  },
  backRightBtnLeft: {
    backgroundColor: 'blue',
    right: 75,
  },
  backRightBtnRight: {
    backgroundColor: 'red',
    right: 0,
  },
  backTextWhite: {
    color: '#FFF',
  },
  noItemFoundImage: {
    height: height / 2, width: width - 40,
  },
  splashStyle: {
    height, width,
  },
  recipeTypeLeft: { flex: 0.8 },
  recipeTypeRight: { flex: 0.2, alignItems: 'flex-end' },
  recipeNameContainer: { flexDirection: 'column', marginTop: 15 },
  marginContainer: { marginTop: 15 },
  rowContainer: { flexDirection: 'row' },
  tagContainer: {
    justifyContent: 'center', borderColor: 'black', marginTop: 10, backgroundColor: '#d3d3d3',
  },
  tagInput: { backgroundColor: '#107498', borderRadius: 10, color: 'white' },
  imageUploadContainer: {
    flexDirection: 'column', alignItems: 'center', justifyContent: 'center', marginLeft: 15,
  },
  uploadText: { fontSize: 12, color: 'white' },
  submitBtnStyle: { fontSize: 16, fontWeight: 'bold', color: 'white' },
  recipeTypeItem: {
    height: 40, borderBottomColor: 'black', borderBottomWidth: 0.4, justifyContent: 'center',
  },
  recipeTypeView: { marginTop: Platform.OS === 'ios' ? 20 : 0 },
  recipeTypeListView: { marginTop: 50, padding: 15 },
  recipeListContainer: { paddingBottom: 30 },
  topbarContainer: {
    position: 'absolute', top: 0, left: 0, right: 0, height: 50, backgroundColor: '#107498',
  },
  topbarView: { alignItems: 'center', justifyContent: 'center', marginTop: 20 },
  topbarView2: {
    alignItems: 'center', justifyContent: 'center', marginTop: 10, flexDirection: 'row',
  },
  topbarView2touchContainer: { flex: 0.2, alignItems: 'center' },
  topbarViewText: { color: 'white', fontWeight: 'bold' },
  recipeTypeLeft2: { flex: 0.8, alignItems: 'center' },
  topbarViewText2: { color: 'white', fontWeight: 'bold', marginRight: 50 },
  emailText: { fontSize: 16 },
  userEmailContainer: { flexDirection: 'column', marginTop: 15 },
  logoutText: { fontSize: 16, fontWeight: 'bold', color: 'white' },
  recipeListItem: {
    height: 70, borderBottomColor: 'black', backgroundColor: 'white', borderBottomWidth: 0.4, justifyContent: 'center', padding: 10, flexDirection: 'row', borderRadius: 5,
  },
  recipeListItemleft: { flex: 0.5, flexDirection: 'column' },
  recipeListItemleftText: { fontSize: 16, fontFamily: 'Menlo-BoldItalic' },
  recipeListItemRight: { flex: 0.5, justifyContent: 'center', alignItems: 'flex-end' },
  recipeListImage: { width: 40, height: 40 },
  hiddenButtonContainer: { flexDirection: 'row', height: 70 },
  recipeListHiddenLeft: { flex: 0.5, justifyContent: 'center' },
  recipeListHiddenMarginLeft: { marginLeft: 20 },
  recipeListHiddenRight: { flex: 0.5, alignItems: 'flex-end', justifyContent: 'center' },
  recipeListHiddenMarginRight: { marginRight: 20 },
  recipeListView: { flex: 1, backgroundColor: '#33ffeb' },
  swipeListStyle: { marginTop: 20 },
  swipeListContainerStyle: { paddingBottom: 100 },
});

export default styles;
